---
- name: Wait for elasticsearch to start
  wait_for:
    port: 9200
    host: localhost
    timeout: 300

- name: Load cleanup policy
  run_once: true
  uri:
    url: http://localhost:9200/_ilm/policy/logstash-cleanup
    method: PUT
    body: "{{ lookup('file', elk_logstash_conf_dir + '/index_management/logstash-cleanup.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"

- name: Edit template if already imported without ILM
  tags: cleanup
  run_once: true
  uri:
    url: http://localhost:9200/_template/logstash
    method: PUT
    body: "{{ lookup('file', elk_logstash_conf_dir + '/index_management/logstash.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"

- name: Apply cleanup policy to existing indices
  failed_when: false
  tags: logstash
  run_once: true
  uri:
    url: http://localhost:9200/logstash-*/_settings
    method: PUT
    body: >
      {
        "index": {
          "lifecycle": {
            "name": "logstash-cleanup"
          }
        }
      }
    body_format: json
    headers:
      Content-Type: "application/json"
