---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}
    server_type: cx31
    image: ${MOLECULE_IMAGE}
provisioner:
  name: ansible
verifier:
  name: testinfra
