---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: ${REPO_NAME}-${OS_VERSION}-${REF}-node1
    server_type: cx31
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - elk
  - name: ${REPO_NAME}-${OS_VERSION}-${REF}-node2
    server_type: cx31
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - elk
provisioner:
  name: ansible
  inventory:
    group_vars:
      elk:
        elk_cluster: true
        elk_group_name: elk
        elk_master_hosts: ${REPO_NAME}-${OS_VERSION}-${REF}-node1
        elk_kibana_extra_vars:
          - SERVER_PUBLICBASEURL=http://some.public.url
verifier:
  name: testinfra
